name: Saludo

on: [push, issues]

jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      push: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "message will be displayed on users' first push"
    
